dashboard:
    path: /
    controller: App\Controller\DashboardController::view

history_main:
    path: /history
    controller: App\Controller\HistoryController::view

history_add:
    path: /history/add
    controller: App\Controller\HistoryController::add

history_change_trade_type:
    path: /history/changeTradeType/{tradeId}
    controller: App\Controller\HistoryController::changeTradeType

history_change_order_type:
    path: /history/changeOrderType/{tradeId}
    controller: App\Controller\HistoryController::changeOrderType

transaction_main:
    path: /corporate-action
    controller: App\Controller\TransactionController::view

transaction_add:
    path: /corporate-action/add
    controller: App\Controller\TransactionController::add

long_main:
    path: /portfolio/long
    controller: App\Controller\LongController::view

long_detail:
    path: /portfolio/long/{symbol}
    controller: App\Controller\LongController::detail

short_main:
    path: /portfolio/short
    controller: App\Controller\ShortController::view

short_detail:
    path: /portfolio/short/{symbol}
    controller: App\Controller\ShortController::detail

option_main:
    path: /portfolio/option
    controller: App\Controller\OptionController::view

option_detail:
    path: /portfolio/option/{symbol}
    controller: App\Controller\OptionController::detail
